//// <auto-generated />
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using Setup.Models;

//#nullable disable

//namespace Setup.Migrations
//{
//    [DbContext(typeof(ContactFormDbContext))]
//    [Migration("20230217121936_InitialCreate")]
//    partial class InitialCreate
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "7.0.3")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("Setup.Models.ContactFormModel", b =>
//                {
//                    b.Property<string>("Email")
//                        .HasColumnType("nvarchar(450)");

//                    b.Property<string>("Message")
//                        .IsRequired()
//                        .HasMaxLength(600)
//                        .HasColumnType("nvarchar(600)");

//                    b.Property<string>("Subject")
//                        .IsRequired()
//                        .HasMaxLength(200)
//                        .HasColumnType("nvarchar(200)");

//                    b.HasKey("Email");

//                    b.ToTable("ContactFormModels");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
