name: Semgrep Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  semgrep-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Semgrep
        run: curl -sSL https://github.com/semgrep/semgrep/releases/download/v0.39.0/semgrep_linux_amd64.tar.gz | tar -xz -C /usr/local/bin

      - name: Run Semgrep Analysis
        run: semgrep --language csharp --file "*.cs" --rules rules.yaml
